project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "Democratic backsiliding in Europe: insights from the V-Dem dataset"
  author: Roberta Zeno
    - AUTHOR1 rz2790
  repo-url: https://github.com/zeno-r/RZ_Final_Project
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true

